### ISSUE TITLE
Compare the TDD and BDD frameworks

### ISSUE THREAD

**Issue by ptrived** [NCSU-CSC510/CMS-module#13]
Comparing the two approaches of development based on parameters

**Comment by anishashetty** [comment]
1. Learning curve for the tools:
   Jbehave: Since neither of the team members were familiar to the tool, the first few days of the project were spent in learning about using the tool, writing stories.
   JUnit and Mockito : The team members were familiar with writing JUnit test cases so writing JUnit test cases wasn't that difficut. Mockito framework was something new. So it took some time to understand Mockito and how and where we can use Mockito framework in our project.
2. Development time : With use of TDD, the initial development time increases which might overshadow the long term gain like software quality etc. With the use of BDD, we can develop test cases faster with users use cases as its main focus. This helps faster development and gives better clarity.

**Comment by anishashetty** [comment]
1. Scope: 
   BDD tests an entire functionality of the system.
   For example, Consider the save posts spec.
   The tests are written for the below functionality:
   Scenario: Save a post (DRAFT)

Given number of posts 1
Given a post with a draft version
When I try to save a post using postid=1, versionid=1
Then the post is updated

Given number of posts 1
Given a post with a published version
When I try to save a post using postid=2, versionid=1
Then the post is not updated

The scope if TDD is only testing a particular method. For example : We have a method say editPost() in PostManager class. So testEditPost() testcase just focuses on if the particular method is giving expected output or not.
1. Granularity: 
   BDD does not focus on how the method for the spec has been implemented. The main focus of BDD is on the user specification. 
   TDD focuses on the specific implementation of the method. TDD is used to test the source code to check whether it returns the desired value or not. It is difficult to write TDD test cases, as it is not always true that the programmer will know the results correctly.
2. Ease of understanding : 
   On camparing the BDD and TDD tests, BDD stories give a clearer understanding on what the method is expected to do.
   TDD on the other hand gives more insight into how the method has been implemented. So to a user who doesn't know the internal implementation, understanding TDD test cases is tough.
3. Interaction level with users: TDD is more developer centric where as BDD is more user centric. So with BDD, user can better understand the test case and verify if the system is producing expected output or not.
